@startuml
left to right direction

actor Visitor
actor RegisteredUser
actor Admin

Admin --|> RegisteredUser : Extends
RegisteredUser --|> Visitor : Extends 

usecase "Browse Catalog" as UC_Browse
usecase "Search Books" as UC_Search
usecase "View Book Details" as UC_ViewBook
usecase "Register" as UC_Register
usecase "Login" as UC_Login

usecase "Logout" as UC_Logout
usecase "Manage Review" as UC_ManageReview
usecase "Write Review" as UC_WriteReview
usecase "Edit Review" as UC_EditReview
usecase "Delete Review" as UC_DeleteReview
usecase "Like Review" as UC_LikeReview
usecase "View Profile" as UC_ViewProfile
usecase "Manage Friends" as UC_ManageFriends
usecase "Send Friend Request" as UC_SendFriendRequest
usecase "Accept Friend Request" as UC_AcceptFriendRequest
usecase "Reject Friend Request" as UC_RejectFriendRequest
usecase "Remove From Friends" as UC_RemoveFromFriends
usecase "Set Reading Status" as UC_Status
usecase "Report Review" as UC_ReportReview

usecase "Update Book Rating" as UC_UpdateRating

usecase "Manage Books" as UC_ManageBooks
usecase "Manage Users" as UC_ManageUsers
usecase "Manage Reviews" as UC_ManageAllReviews
usecase "Add Book" as UC_AddBook
usecase "Delete Book" as UC_DeleteBook
usecase "Edit Description" as UC_EditDescription
usecase "Ban User" as UC_BanUser
usecase "Mod User" as UC_ModUser
usecase "Delete Reviews" as UC_DeleteReviews

Visitor --> UC_Browse
Visitor --> UC_Search
Visitor --> UC_ViewBook
Visitor --> UC_Register
Visitor --> UC_Login

RegisteredUser --> UC_Logout
RegisteredUser --> UC_ManageReview
RegisteredUser --> UC_LikeReview
RegisteredUser --> UC_ManageFriends
RegisteredUser --> UC_Status
RegisteredUser --> UC_ReportReview

Admin --> UC_ManageBooks
Admin --> UC_ManageUsers
Admin --> UC_ManageAllReviews

UC_WriteReview ..> UC_UpdateRating : Use
UC_EditReview ..> UC_UpdateRating : Use
UC_DeleteReview ..> UC_UpdateRating : Use

UC_DeleteBook ..> UC_DeleteReviews : Use
UC_BanUser ..> UC_DeleteReviews : Use
UC_DeleteReviews ..> UC_UpdateRating : Use

UC_ManageFriends  <|-- UC_SendFriendRequest : Extends
UC_ManageFriends  <|-- UC_AcceptFriendRequest : Extends
UC_ManageFriends  <|-- UC_RejectFriendRequest : Extends
UC_ManageFriends  <|-- UC_RemoveFromFriends : Extends

UC_ManageReview <|-- UC_WriteReview : Extends
UC_ManageReview <|-- UC_EditReview : Extends
UC_ManageReview <|-- UC_DeleteReview : Extends

UC_ManageBooks <|-- UC_AddBook : Extends
UC_ManageBooks <|-- UC_DeleteBook : Extends
UC_ManageBooks <|-- UC_EditDescription : Extends

UC_ManageUsers <|-- UC_BanUser : Extends
UC_ManageUsers <|-- UC_ModUser : Extends

UC_ManageAllReviews  <|-- UC_DeleteReviews : Extends

@enduml
